#include "colorindex.h"

void colorindex_init()
{
	/* 
	init_pair(COLORINDEX_NORMAL, COLOR_WHITE, COLOR_BLACK);

	init_pair(COLORINDEX_ERRORCODE, COLOR_RED, COLOR_BLACK);

	init_pair(COLORINDEX_SELECTITEM, COLOR_YELLOW, COLOR_BLACK);

	init_pair(COLORINDEX_CHESSBOARD, COLOR_BLACK, COLOR_YELLOW);
	init_pair(COLORINDEX_CHESSBOARDENEMY, COLOR_RED, COLOR_YELLOW);

	init_pair(COLORINDEX_READYBTNTEXT, COLOR_WHITE, COLOR_BLACK);
	init_pair(COLORINDEX_READYBTNFRAME, COLOR_RED, COLOR_BLACK);

	init_pair(COLORINDEX_STARTMENUFRAME, COLOR_MAGENTA, COLOR_BLACK);
	init_pair(COLORINDEX_STARTMENUTEXT, COLOR_CYAN, COLOR_BLACK);

	init_pair(COLORINDEX_ALLBLACK, COLOR_BLACK, COLOR_BLACK);
	*/

	init_pair(COLORINDEX_NORMAL, COLOR_BLACK, COLOR_YELLOW);

	init_pair(COLORINDEX_ERRORCODE, COLOR_RED, COLOR_YELLOW);

	init_pair(COLORINDEX_SELECTITEM, COLOR_YELLOW, COLOR_YELLOW);

	init_pair(COLORINDEX_CHESSBOARD, COLOR_BLACK, COLOR_YELLOW);
	init_pair(COLORINDEX_CHESSBOARDENEMY, COLOR_RED, COLOR_YELLOW);

	init_pair(COLORINDEX_READYBTNTEXT, COLOR_WHITE, COLOR_YELLOW);
	init_pair(COLORINDEX_READYBTNFRAME, COLOR_RED, COLOR_YELLOW);

	init_pair(COLORINDEX_STARTMENUTEXT, COLOR_MAGENTA, COLOR_YELLOW);
	init_pair(COLORINDEX_STARTMENUFRAME, COLOR_CYAN, COLOR_YELLOW);

	init_pair(COLORINDEX_BKGDWHITE, COLOR_BLACK, COLOR_WHITE);
	init_pair(COLORINDEX_BKGDBLUE, COLOR_BLACK, COLOR_CYAN);
	init_pair(COLORINDEX_BKGDRED, COLOR_BLACK, COLOR_RED);
	init_pair(COLORINDEX_BKGDYELLOW, COLOR_BLACK, COLOR_YELLOW);
	init_pair(COLORINDEX_BKGDGREEN, COLOR_BLACK, COLOR_GREEN);

	init_pair(COLORINDEX_TEXTGREEN, COLOR_GREEN, COLOR_YELLOW);
	init_pair(COLORINDEX_TEXTCYAN, COLOR_CYAN, COLOR_YELLOW);
	init_pair(COLORINDEX_TEXTMAGENTA, COLOR_MAGENTA, COLOR_YELLOW);
	init_pair(COLORINDEX_TEXTWHITE, COLOR_WHITE, COLOR_YELLOW);

	init_pair(COLORINDEX_ALLBLACK, COLOR_BLACK, COLOR_BLACK);
	init_pair(COLORINDEX_ALLGREEN, COLOR_GREEN, COLOR_GREEN);

}

void godmode_color_init()
{
	for (int i = 0; i <= COLORINDEX_NTOTAL; i++)
		init_pair(i, COLOR_RED, COLOR_BLACK);

	// extra
	init_pair(COLORINDEX_ALLGREEN, COLOR_CYAN, COLOR_BLACK);
}