#pragma once
#ifndef _COLORINDEX_H_
#define _COLORINDEX_H_

#include "curses.h"

#define COLORINDEX_NTOTAL 15

#define COLORINDEX_NORMAL_UNCHANGED 0
#define COLORINDEX_NORMAL 1
#define COLORINDEX_CHESSBOARD 2
#define COLORINDEX_READYBTNFRAME 3
#define COLORINDEX_READYBTNTEXT 4
#define COLORINDEX_ERRORCODE 5
#define COLORINDEX_SELECTITEM 6
#define COLORINDEX_STARTMENUFRAME 7
#define COLORINDEX_STARTMENUTEXT 8
#define COLORINDEX_CHESSBOARDENEMY 9
#define COLORINDEX_BKGDWHITE 10
#define COLORINDEX_BKGDBLUE 11
#define COLORINDEX_BKGDRED 12
#define COLORINDEX_BKGDYELLOW 13
#define COLORINDEX_BKGDGREEN 14
#define COLORINDEX_TEXTRED COLORINDEX_ERRORCODE
#define COLORINDEX_TEXTYELLOW COLORINDEX_SELECTITEM
#define COLORINDEX_TEXTBLUE COLORINDEX_STARTMENUFRAME
#define COLORINDEX_TEXTPURPLE COLORINDEX_STARTMENUTEXT
#define COLORINDEX_TEXTGREEN 15
#define COLORINDEX_TEXTCYAN 16
#define COLORINDEX_TEXTMAGENTA 17
#define COLORINDEX_TEXTWHITE 18
#define COLORINDEX_TEXTBLACK COLORINDEX_NORMAL

#define COLORINDEX_ALLBLACK 50
#define COLORINDEX_ALLGREEN 51

void colorindex_init();

void godmode_color_init();

#endif